### ISSUE TITLE
Indexing CouchDB attachments

### ISSUE THREAD

**Issue by dadoonet** [elasticsearch/elasticsearch-river-couchdb#25]
Idea is to index attachment files from CouchDb in addition of JSon documents

**Comment by chrhenne** [comment]
Are there any future plans for this branch/issue, or any other official or community-driven initiatives for supporting indexing of attachment files from couch? We want to use ES to provide full-text search in  PDF documents stored as CouchDB attachments, but there seems to be little or none activity on that front recently.

**Comment by dadoonet** [comment]
I believe this is something we most likely won't support as a `_river` but it could be implemented in the future in logstash.

Closing.
