### ISSUE TITLE
"IndexMissingException[[_river] missing]" when creating rivers on ES 1.2.1, couchdb-river 2.0.0

### ISSUE THREAD

**Issue by Japh** [elasticsearch/elasticsearch-river-couchdb#70]
When trying to create a river, I got the following error message:

```
{"error":"IndexMissingException[[_river] missing]","status":404}
```

If I attempted to `curl -XGET 'localhost:9200/_river'`, I would see:

```
No handler found for uri [/_river] and method [GET]
```

The same fix as mentioned in elasticsearch/elasticsearch-river-rabbitmq#40 works for me.

I run `curl -XPUT 'localhost:9200/_river'`, and then I can create the river with no error and an expected acknowledgement.

**Comment by dadoonet** [comment]
IIRC this has been fixed in elasticsearch itself. Closing but feel free to reopen if it's not the case.
