### ISSUE TITLE
Basic authentification failure

### ISSUE THREAD

**Issue by guillaumek** [elasticsearch/elasticsearch-river-couchdb#73]
Hello,

i am using your plugin version 2.3.0  with elasticsearch 1.3.2 and couchdb v 1.5.0
I have secured my database so only a certain role can access. Then when i create my river i added user and password value.
$data = array(
            "type" => "couchdb",
            "couchdb" => array(
                "host" => "localhost",
                "port" => 5984,
                "db" => "track",
                "filter" => null,
                "user" => "music",
                "password" => "musicadmin"
            ),
            "index" => array(
                "index" => "track",
                "type" => "track",
                "bulk_size" => "100",
                "bulk_timeout" => "10ms"
            )
        );

few other points: when i unsecure my db and remove the credantials it works :)
thank for your help.

PS: great plugin, great job :)

 In my couch.log file i have the following trace:

{error_report,<0.31.0>,
                       {<0.16515.0>,crash_report,
                        [[{initial_call,
                           {mochiweb_acceptor,init,
                            ['Argument__1','Argument__2','Argument__3']}},
                          {pid,<0.16515.0>},
                          {registered_name,[]},
                          {error_info,
                           {error,
                            {case_clause,bad_accept_header},
                            [{couch_httpd,error_headers,4,
                              [{file,"couch_httpd.erl"},{line,870}]},
                             {couch_httpd,send_error,2,
                              [{file,"couch_httpd.erl"},{line,914}]},
                             {couch_httpd,handle_request_int,5,
                              [{file,"couch_httpd.erl"},{line,365}]},
                             {mochiweb_http,headers,5,
                              [{file,"mochiweb_http.erl"},{line,94}]},
                             {proc_lib,init_p_do_apply,3,
                              [{file,"proc_lib.erl"},{line,239}]}]}},
                          {ancestors,
                           [couch_httpd,couch_secondary_services,
                            couch_server_sup,<0.32.0>]},
                          {messages,[]},
                          {links,[<0.107.0>,#Port<0.7394>]},
                          {dictionary,
                           [{couch_rewrite_count,0},
                            {mochiweb_request_cookie,[]}]},
                          {trap_exit,false},
                          {status,running},
                          {heap_size,6772},
                          {stack_size,27},
                          {reductions,5875}],
                         []]}}

**Comment by dadoonet** [comment]
Thank you @cheleb for confirming it is working with more recent versions.
I'm closing for now but feel free to reopen if it still an issue with latest releases.
