### ISSUE TITLE
Ability to specify two hosts

### ISSUE THREAD

**Issue by thomaswitt** [elasticsearch/elasticsearch-river-couchdb#8]
In a couched master-master-replication setup, it should be possible to supply two hostnames for the river. If elastic search can't reach the first river anymore because the first couchdb server went down, it should automatically get the changes feed from the second couchdb server.

**Comment by emptyflask** [comment]
IMO this is outside the scope of a river plugin; a load balancing proxy in front of your couch hosts would probably be a better solution.

**Comment by dadoonet** [comment]
I do agree with @emptyflask. This is something that could be solved outside couchdb river itself.
That being said, if it's a useful feature, I would recommend to open the same demand in [Logstash](https://github.com/logstash-plugins/logstash-input-couchdb_changes).

Closing here as it won't most likely be implemented.
