### ISSUE TITLE
Could not find artifact org.elasticsearch:elasticsearch-parent:pom:2.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by micovery** [elasticsearch/elasticsearch-river-couchdb#83]
Hey, I am fairly new to using maven as a build system. I forked and cloned the repo, and tried to build the master branch as per the README instructions with:

```
  mvn clean install
```

However I am getting this error:

```
$ mvn clean install
[INFO] Scanning for projects...
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.elasticsearch:elasticsearch-river-couchdb:3.0.0-SNAPSHOT (/home/steam/couchdbriver/elasticsearch-river-couchdb/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Could not find artifact org.elasticsearch:elasticsearch-parent:pom:2.0.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 7, column 13 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
```

Looking at the pom history, it seems that this is because of a fairly recent change. Is this some sort of private dependency that is not available?

Should I not be building from the master branch?

I am trying setup the development environment to be able to build, and test this plugin. I want to make a minor modification to allow the ID field to be overwritten.

EDIT: Building from the 1.4 branch works fine.

**Comment by dadoonet** [comment]
Should be fixed by 5eee3d026fdf0158816c2d48e04b0e6ee8ba36db
