### ISSUE TITLE
release snapshot 2.4.2

### ISSUE THREAD

**Issue by guillaumek** [elasticsearch/elasticsearch-river-couchdb#87]
Hello,

I was wondering if it could be possible to add the link for snapshot 2.4.2, because to make the river working with es 1.4.2, i needed to build the snapshot.

Best Guillaume.

**Comment by dadoonet** [comment]
2.4.1 should work fine with elasticsearch 1.4.2. It does not?

**Comment by guillaumek** [comment]
well it didn't but let me check again then, maybe a mistake on my side
thanks.
